/* Generated by BIN2S - please don't edit directly */
	.section .rodata
	.balign 4
	.global test_txt_size
	.global test_txt
test_txt:
	.byte  72,101,108,108,111, 44, 87,111,114,108,100, 33

	.global test_txt_end
test_txt_end:

	.balign 4
test_txt_size: .int 12
